package mui.core.grid;

enum abstract GridClassKey(String) to String {
	var Container = "container";
	var Item = "item";
	var ZeroMinWidth = "zeroMinWidth";
	var DirectionXSColumn = "direction-xs-column";
	var DirectionXSColumnReverse = "direction-xs-column-reverse";
	var DirectionXSRowReverse = "direction-xs-row-reverse";
	var WrapXSNoWrap = "wrap-xs-nowrap";
	var WrapXSWrapReverse = "wrap-xs-wrap-reverse";
	var AlignItemsXSCenter = "align-items-xs-center";
	var AlignItemsXSStart = "align-items-xs-flex-start";
	var AlignItemsXSEnd = "align-items-xs-flex-end";
	var AlignItemsXSBaseline = "align-items-xs-baseline";
	var AlignContentXSCenter = "align-content-xs-center";
	var AlignContentXSFlexStart = "align-content-xs-flex-start";
	var AlignContentXSFlexEnd = "align-content-xs-flex-end";
	var AlignContentXSSpaceBetween = "align-content-xs-space-between";
	var AlignContentXSSpaceAround = "align-content-xs-space-around";
	var JustifyXSCenter = "justify-xs-center";
	var JustifyXSFlexEnd = "justify-xs-flex-end";
	var JustifyXSSpaceBetween = "justify-xs-space-between";
	var JustifyXSSpaceAround = "justify-xs-space-around";
	var JustifyXSSpaceEvenly = "justify-xs-space-evenly";
	var SpacingXS8 = "spacing-xs-8";
	var SpacingXS16 = "spacing-xs-16";
	var SpacingXS24 = "spacing-xs-24";
	var SpacingXS32 = "spacing-xs-32";
	var SpacingXS40 = "spacing-xs-40";
	var GridXSAuto = "grid-xs-auto";
	var GridXSTrue = "grid-xs-true";
	var GridXS1 = "grid-xs-1";
	var GridXS2 = "grid-xs-2";
	var GridXS3 = "grid-xs-3";
	var GridXS4 = "grid-xs-4";
	var GridXS5 = "grid-xs-5";
	var GridXS6 = "grid-xs-6";
	var GridXS7 = "grid-xs-7";
	var GridXS8 = "grid-xs-8";
	var GridXS9 = "grid-xs-9";
	var GridXS10 = "grid-xs-10";
	var GridXS11 = "grid-xs-11";
	var GridXS12 = "grid-xs-12";
}
